name: Daily Commit Automation

on:
  schedule:
    - cron: "30 18 * * *"  # Runs daily at 18:30 UTC (Adjust time as needed)

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git with 23f1002071@ds.study.iitm.ac.in
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "23f1002071@ds.study.iitm.ac.in"

      - name: Make Changes
        run: |
          echo "Last run: $(date)" > last_run.txt
          git add last_run.txt
          git commit -m "Automated commit: $(date)"
          git push
